### PR TITLE
feat: 🎸 add triangle shapes to home page

### PR DESCRIPTION
**Pull request by codybarr**
Closes: #54

### CODE REVIEW

**Comment by codybarr** [comment]
Hey guys, this build is failing because I stupidly put the `css` file for the index page in the `pages` directory (which Gatsby doesn't like).

image

Where should this guy go?

image

**Comment by timhwang21** [comment]
Hmmm maybe redux container pattern? Can start moving towards pages simply
having a gql query and rendering a single imported component? (And some
data massaging) Style would then be colocated with imported component.

**Comment by a-trost** [comment]
I get that they're only extended `box` components but I feel like `HeroSection` and `EventSection` could just exist as components in `src/components/homepage/`.  I feel like that's the lowest/cleanest refactor here.

**Comment by codybarr** [comment]
> I get that they're only extended `box` components but I feel like `HeroSection` and `EventSection` could just exist as components in `src/components/homepage/`. I feel like that's the lowest/cleanest refactor here.

@a-trost How does this look? e1da8a8

**Comment by a-trost** [comment]
I was thinking having a .js and .css.js file, but I guess the js file doesn't really make sense, so yeah this works for me. Looks good, rebasing and merging in.

**Pull request merged**
